server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  config:
    import: application-secret.yml
  cloud:
    gateway:
      routes: # \uB77C\uC6B0\uD305 \uC124\uC815
        - id: board-service  # \uAD6C\uBD84\uD558\uAE30 \uC704\uD55C id\uAC12\uC73C\uB85C \uC784\uC758\uB85C \uC791\uC131\uD574\uB3C4 \uBB34\uAD00
          uri: lb://BOARD-SERVICE  # \uC720\uB808\uCE74\uC5D0 \uB4F1\uB85D\uD55C \uC11C\uBE44\uC2A4 \uBA85
          predicates: # \uB77C\uC6B0\uD305 \uC870\uAC74
            - Path=/api/boards/**  #  /api/boards/ \uC544\uB798\uB85C \uC694\uCCAD\uC774 \uB4E4\uC5B4\uC654\uC744 \uB54C \uB77C\uC6B0\uD305\uD558\uB3C4\uB85D

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.url}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
