server:
  port: 8761

spring:
  application:
    name: eureka-server # ??????? ?? -> ?? ??? ???? ?? ?? ???? ???
  config:
    import: application-secret.yml

eureka:
  instance:
    hostname: ${eureka.hostname}
  client:
    register-with-eureka: true # ??? ?? ????? ??? ???
    fetch-registry: true # ??? ????? ?????? ??? ????? ??? ???