server:
  port: 8081

spring:
  application:
    name: board-service
  config:
    import: application-secret.yml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.url} # ?? ?? EUREKA_URL? ?? ???? ?? ????, ??? ??? ??? http://localhost:8761/eureka/? ??
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Eureka ??? ??? ? ??? ????? ??? ID? ???? ??

management:
  endpoint:
    shutdown:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG